name: Update Pi-hole Blocklist Daily

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-blocklist:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and convert AdGuard filter to Pi-hole domains
        shell: pwsh
        run: |
          $url = "https://raw.githubusercontent.com/AdguardTeam/HostlistsRegistry/refs/heads/main/filters/other/filter_39_DandelionSprouts_AntiPushNotifications/filter.txt"
          $outputFile = "pihole_blocklist.txt"
          $content = Invoke-WebRequest -Uri $url -UseBasicParsing | Select-Object -ExpandProperty Content
          $domainPattern = '^\|\|?([a-z0-9.-]+\.[a-z]{2,})(\^)?$'
          $domains = @{}

          foreach ($line in $content -split "`n") {
            $trimmed = $line.Trim()
            if ($trimmed -match $domainPattern) {
              $domain = $matches[1].ToLower()
              $domains[$domain] = $true
            }
          }

          # Ausgabe wie viele Domains extrahiert wurden
          Write-Output "Extracted $($domains.Count) domains."

          # Datei speichern
          $domains.Keys | Sort-Object | Out-File -FilePath $outputFile -Encoding ASCII

          # Verzeichnisinhalt auflisten
          Write-Output "Current directory files:"
          Get-ChildItem -File

          # Inhalt der erstellten Datei anzeigen (erste 10 Zeilen)
          Write-Output "First 10 lines of output file:"
          Get-Content $outputFile -TotalCount 10

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pihole_blocklist.txt
          git diff --quiet || (git commit -m "Auto-update Pi-hole blocklist" && git push)
